[general]
import = [
    "C:\\Users\\user\\AppData\\Roaming\\alacritty\\themes\\themes\\kanagawa_dragon.toml"]

[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xd19a66"

[colors.normal]
black = "0x0e1013"
blue = "0x4fa6ed"
cyan = "0x48b0bd"
green = "0x8ebd6b"
magenta = "0xc678dd"
red = "0xe55561"
white = "0xabb2bf"
yellow = "0xe2b86b"

[colors.primary]
background = "0x1f2329"
foreground = "0xd5d7de"

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
LANG = "en_US.UTF-8"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[window]
decorations = "None"
opacity = 0.97
dynamic_padding = true
startup_mode = "Windowed"
position = { x = 5, y = 5 }
dimensions = { columns = 211, lines = 48 }

[window.padding]
x = 5
y = 5

[cursor]
style = { shape = "Block", blinking = "Always" }
vi_mode_style = { shape = "Block", blinking = "Always" }
blink_interval = 500
blink_timeout = 0

[terminal.shell]
program = "wsl"
args = [
    "-d",
    "Debian",
    "--cd",
    "~"
]
